### ISSUE TITLE
几点小疑问

### ISSUE THREAD

**Issue by zqlmps** [zhiyiYo/Fucking-ZJU-Blue-Code#1]
这个程序很不错，我在本地成功运行了，但有以下几个疑问，希望您能能解答一下，谢谢！

1. 为什么需要登录呢？这个程序生成的二维码，与 GitHub 上另一个 [repo](https://github.com/beta591414/-ZJUbluecode) 直接套一张二维码图片的区别是什么啊？
2. 如果从 ZJU 系统中登录的账号是灰码，那么这个程序生成的蓝码可以刷开校门口的机器吗？
3. 通过扫描二维码，得到其中的信息是 `jT6tmuodGqJ***` 的一串字符，这是不是用了某种加密方式呢？

再次感谢！

**Comment by zhiyiYo** [comment]
1. 二维码数据被后端加密过，我无法破解，所以是从后端拿的数据
2. 灰码内部的数据是无效的，不能刷开门禁
3. 这个项目的目的是如果你有蓝马，就可以让别人在浏览器用你的码而不需要截图或者在它手机上登你的钉钉账号

**Comment by zqlmps** [comment]
好的，非常感谢！

另外蓝码的样式有点小调整，也许可以更新一下（不过问题也不大）。

**Comment by zhiyiYo** [comment]
问题不大，以后有时间更新一下

**Comment by zqlmps** [comment]
请问蓝码是否有时效性？我扫描过自己二维码几次，其中的信息不相同。

假如有时效性的话，如果生成静态文件部署到服务器，是不是每隔一段时间需要重新构建一下？

**Comment by zhiyiYo** [comment]
蓝马有时效性，不需要重新构建，每次访问页面都会重新去后台获取数据

**Comment by zqlmps** [comment]
回复太快了，灰常感谢 👍
